apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false # Don't try to push the image to a registry, once built
  artifacts:
    - image: tmprimitivo/concert-tickets-app/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: . # where to sync the files to inside the running container
    - image: tmprimitivo/concert-tickets-app/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: tmprimitivo/concert-tickets-app/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: tmprimitivo/concert-tickets-app/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: tmprimitivo/concert-tickets-app/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .