apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false # Don't try to push the image to a registry, once built
  artifacts:
    - image: tmprimitivo/concert-tickets-app_auth
      context: auth
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          GITHUB_AUTH_TOKEN: "{{.GITHUB_AUTH_TOKEN}}"
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: . # where to sync the files to inside the running container
    - image: tmprimitivo/concert-tickets-app_client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: tmprimitivo/concert-tickets-app_tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          GITHUB_AUTH_TOKEN: "{{.GITHUB_AUTH_TOKEN}}"
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: tmprimitivo/concert-tickets-app_orders
      context: orders
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          GITHUB_AUTH_TOKEN: "{{.GITHUB_AUTH_TOKEN}}"
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: tmprimitivo/concert-tickets-app_expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          GITHUB_AUTH_TOKEN: "{{.GITHUB_AUTH_TOKEN}}"
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: tmprimitivo/concert-tickets-app_payments
      context: payments
      docker:
        dockerfile: Dockerfile
        buildArgs: 
          GITHUB_AUTH_TOKEN: "{{.GITHUB_AUTH_TOKEN}}"
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .