apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: tmprimitivo/concert-tickets-app_expiration
        env:
          - name: NATS_URL
            value: 'http://nats-service:4222'
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name # use pod's name
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: REDIS_HOST
            value: expiration-redis-service
        
# ---

# Not necessary here. Expiration service relies on NATS, and emits events, that's all.
# Doesn't need to be reached out

# apiVersion: v1
# kind: Service
# metadata:
#   name: expiration-service
# spec:
#   selector:
#     app: expiration