apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: tmprimitivo/concert-tickets-app_payments
        env:
          - name: MONGO_URI
            value: 'mongodb://payments-mongo-service:27017'
          - name: NATS_URL
            value: 'http://nats-service:4222'
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name # use pod's name
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: JWT_KEY
            valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: stripe-secret
                key: STRIPE_KEY
                  
        
---
# Defaults to ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  ports:
  - name: payments
    protocol: TCP
    port: 3000
    targetPort: 3000
