name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: orders
          push: true
          tags: tmprimitivo/concert-tickets-app_orders
          build-args: |
            GITHUB_AUTH_TOKEN=${{secrets.GITHUB_TOKEN}}



  