name: deploy-manifest

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"


jobs:
  deploy_config:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
      - name: Get D'O cluster active context to kubectl
        uses: doctl kubernetes cluster kubeconfig save concert-tickets-app 

      - name: Apply k8s config
        uses: kubectl apply -f infra/k8s -f infra/k8s-prod