name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: tickets
          push: true
          tags: tmprimitivo/concert-tickets-app_tickets
          build-args: |
            GITHUB_AUTH_TOKEN=${{secrets.GITHUB_TOKEN}}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
      - name: Get D'O cluster active context to kubectl
        run: doctl kubernetes cluster kubeconfig save concert-tickets-app 

      - name: Restart tickets deployment
        run: kubectl rollout restart deployment tickets-depl

  