name: tests-payments
on:
  pull_request:
    paths:
      - 'payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    steps:
    - uses: actions/checkout@v2
    - run: cd payments && npm i && npm run test:ci