name: tests
on:
  pull_request:
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: ferluisxd/create-npmrc@3
       with:
          org_name: applinh
          auth_token: ${{ secrets.GITHUB_TOKEN }}
     - run: cp .npmrc auth/.npmrc
     - run: cd auth && npm i && npm run test:ci