name: tests-auth
on:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    steps:
    - uses: actions/checkout@v2
    - run: cd auth && npm i && npm run test:ci